export const ADDED = 'todos/added'
export const TOGGLED = 'todos/toggled'
export const COLORSELECTED = 'todos/colorselected'
export const DELETED = 'todos/deleted'
export const COMPLETEDALL = 'todos/completedall'
export const CLEARCOMPLETED = 'todos/clearcompleted'